# Generated by Django 3.2.25 on 2024-07-29 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=255)),
                ('bath', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('image_appart', models.ImageField(upload_to='media')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.DateTimeField(blank=True)),
                ('date_out', models.DateTimeField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.appartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppartImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.appartment')),
            ],
        ),
    ]
