# Generated by Django 5.0.6 on 2024-07-15 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=255)),
                ('bath', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('image_appart', models.ImageField(upload_to='media')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.DateTimeField(blank=True)),
                ('date_out', models.DateTimeField(blank=True)),
                ('appart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.appartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
