# Generated by Django 3.2.25 on 2024-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adult',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='child',
            field=models.IntegerField(default=0),
        ),
    ]
