# Generated by Django 3.2.25 on 2024-08-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingApp.category'),
            preserve_default=False,
        ),
    ]
