# Generated by Django 3.2.25 on 2024-08-10 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_room_category_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentroom',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
