# Generated by Django 3.2.25 on 2024-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
