# Generated by Django 3.2.25 on 2024-07-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0006_appartment_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.appartment')),
            ],
        ),
    ]
