# Generated by Django 3.2.25 on 2024-07-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0008_auto_20240724_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartment',
            name='list_images',
        ),
        migrations.AddField(
            model_name='appartimages',
            name='appartement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingApp.appartment'),
            preserve_default=False,
        ),
    ]
