# Generated by Django 3.2.25 on 2024-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0009_auto_20240724_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('appart', 'Appartement'), ('dup', 'duplex'), ('vill', 'villa')], max_length=255)),
            ],
        ),
    ]
