# Generated by Django 3.2.25 on 2024-07-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0010_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
